### ISSUE TITLE
CSS enhancement: Beautify our dashboard

### ISSUE THREAD

**Issue by baristaGeek** [watermelontools/watermelon#248]
Some work could be done, most notably on the sidebar. Suggestion are more than welcome :)

**Comment by Omm2005** [comment]
Can i work on it?

**Comment by baristaGeek** [comment]
@Omm2005 absolutely! Contributions are more than welcome, and if there's anything we can help with, please let us know.

**Comment by Omm2005** [comment]
Just the Dashboard?

**Comment by EstebanDalelR** [comment]
Hey!
For local host you can copy the cookie you get in production.

**Comment by Omm2005** [comment]
How to do that?

**Comment by baristaGeek** [comment]
Hey @Omm2005 in Chrome you can: 

1. Auth as a normal end user at app.watermelontools.com
2. Open the developer console. Click the Application tab
3. Then at the treeview at the left, find the Storage -> Cookies section
4. There are a bunch of Name, Value pairs. Copy them so you paste them on localhost:3000
5. Run Watermelon on localhost:3000, then just create the Names and paste the Values. 

CC: @EstebanDalelR please correct me if there's something wrong.

**Comment by baristaGeek** [comment]
I just did this on #339
