### ISSUE TITLE
Watermelon as a team tool

### ISSUE THREAD

**Issue by baristaGeek** [watermelontools/watermelon#276]
Right now our GitHub app contextualizes pull requests individually (only for the person who authorized Watermelon). These tools are expected to osmote information as a team: One person authorizes, and then everyone sees value.

To change this, we need to modify the stored procedure that searches for the token per username that calls getCodeContext, so that it searches for a "token per org" instead of "token per user".

**Comment by EstebanDalelR** [comment]
On it.

**Comment by baristaGeek** [comment]
🎉🎉 closed with #326
