### ISSUE TITLE
Bugfix: Settings page doesn't have a proper behavior

### ISSUE THREAD

**Issue by baristaGeek** [watermelontools/watermelon#344]
When I navigate to the settings page, it doesn't have the sidebar nor the dark theme. 

https://watermelonsudo.slack.com/files/U02779T4TDL/F062SH8NK3R/screen_recording_2023-10-27_at_4.08.18_pm.mov

**Comment by EstebanDalelR** [comment]
Fixed in #348

**Comment by baristaGeek** [comment]
Thanks @EstebanDalelR looks great
