### ISSUE TITLE
Deactivate comments for PRs from bots

### ISSUE THREAD

**Issue by cleder** [watermelontools/watermelon#373]
It is already implemented in part as it reports:

```
WatermelonAI Summary
AI Summary deactivated by pre-commit-ci[bot]
```
but it still tries to figure out Prs and tickets.

I'd prefer that for bot PRs watermelon could just not comment at all.
https://github.com/cleder/pygeoif/pull/190#issuecomment-1808519743

**Comment by baristaGeek** [comment]
We should definitely do that. Thanks for your feedback @cleder

**Comment by baristaGeek** [comment]
@cleder this change has been included in today's release. Please let us know how if it behaves fine!

**Comment by cleder** [comment]
works as expected
