### ISSUE TITLE
Deactivate comments for non-existent services

### ISSUE THREAD

**Issue by cleder** [watermelontools/watermelon#374]
the comments:
```
No results found in Jira Tickets :(
No results found in Confluence Docs :(
No results found in Slack Threads :(
No results found in Notion Pages :(
No results found in Linear Tickets :(
No results found in Asana Tasks :(
``` 
are not helpful, it would be nice if I could disable them.

maybe setting the number to 0 in https://app.watermelontools.com/settings:
![image](https://github.com/watermelontools/watermelon/assets/1218010/b831a97f-fec3-428a-ba09-7f5737579fb9)

or deactivating them in https://app.watermelontools.com/ 
could get rid of them?

**Comment by baristaGeek** [comment]
I can also pick this up. Thanks @cleder

**Comment by EstebanDalelR** [comment]
I'm doing it, expect it by middle of next week

**Comment by baristaGeek** [comment]
@cleder we just merged the PR that allows users to do this: https://github.com/watermelontools/watermelon/pull/402

It will be out in the next version. Would love to get your feedback!
