### ISSUE TITLE
How to active WatermelonAI Summary in Github App?

### ISSUE THREAD

**Issue by Kcih4518** [watermelontools/watermelon#383]
Whenever I try to use Watermelon, I find the AI summary is always deactivated.
![image](https://github.com/watermelontools/watermelon/assets/24835719/1aabad90-cbcc-48c1-9b72-5aecb914c205)

I have setting active in the Watermelon dashboard but it still does not work for me.

![image](https://github.com/watermelontools/watermelon/assets/24835719/edb62240-77d0-4e89-b70b-820e69e5437d)

How can I enable the AI summary?

**Comment by baristaGeek** [comment]
Hi @Kcih4518 we're currently working on a new settings window that will make this more reliable. We'll let you know once it's ready cc: @EstebanDalelR 

Thanks for letting us know.

**Comment by JasonMarechal25** [comment]
A colleague of mine has the same issue : https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/1813#issuecomment-1847217041

I don't. The difference is that I have installed watermelon on my side and for the team. I don't know if it means that every user in a team must install the app too

**Comment by baristaGeek** [comment]
@Kcih4518 We just merged the PR that allows users to do this in a reliable way https://github.com/watermelontools/watermelon/pull/402 expect in the next release (2.1.6). Would love to get your feedback!
