### ISSUE TITLE
Install it on organization repository

### ISSUE THREAD

**Issue by victor-heliomar** [watermelontools/watermelon#406]
I have an organization that opened with some friends for work on personal projects and would like to install it there.

When I am setting up the watermelon for code review tool I am only able to install it for my personal projects, is there any way to install it on the organization?

**Comment by baristaGeek** [comment]
Hey @victor-heliomar more than happy to help :) 

Are you an owner of the organization you have with your friends? If so, you should be able to see such org in the list of possible orgs to authorize Watermelon into. If that's the case and you're not seeing the org, can you. please post a screenshot?

**Comment by victor-heliomar** [comment]
> Hey @victor-heliomar more than happy to help :)
> 
> Are you an owner of the organization you have with your friends? If so, you should be able to see such org in the list of possible orgs to authorize Watermelon into. If that's the case and you're not seeing the org, can you. please post a screenshot?

Hi! I just found a way to install it, only that the flow was new for me.

In case anyone needs it, 

1. I needed to go to github marketplace https://github.com/marketplace/watermelon-context
2. Then clicked on Set up a new plan
3. Install it for free
4. In that view, I needed to change my user for the organization
5. Then install it and you will be able to install it on the repo of the organization that you want

**Comment by baristaGeek** [comment]
@victor-heliomar gotcha! That's the way to do it. 

Where on our side should we make this more clear? Any suggestion for us?
