### ISSUE TITLE
Console log detection too lax. Detects log where there's none

### ISSUE THREAD

**Issue by JasonMarechal25** [watermelontools/watermelon#409]
Hello
Bot detects logs where there is none. Hera an example : https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/1813/files/058a5b777dc17237dc1f599000f801348b8115ff#r1422186931

**Comment by baristaGeek** [comment]
Hey @JasonMarechal25 thanks for your input! We're fixing this right now. Please bear with us and expect a fix this week or the next.

**Comment by baristaGeek** [comment]
@JasonMarechal25 I sent this PR, would love to get your feedback! https://github.com/watermelontools/watermelon/pull/413
