### ISSUE TITLE
Sign up page: Image is broken 

### ISSUE THREAD

**Issue by baristaGeek** [watermelontools/watermelon#418]
In app.watermelontools.com, after you click the "Sign In" button, you see this broken image. Our logo should be there. 

<img width="582" alt="Screenshot 2023-12-15 at 4 36 26 PM" src="https://github.com/watermelontools/watermelon/assets/8325094/d5e5efda-cf2c-494b-8e3e-516207b85b7d">

**Comment by gvijay4321** [comment]
I would like to take up this issue.
Either we have  a reduced size png or 
Change the image url in route.ts

**Comment by EstebanDalelR** [comment]
Closed in #427
