### ISSUE TITLE
Build the first version of a RegEx to detect PII data 

### ISSUE THREAD

**Issue by baristaGeek** [watermelontools/watermelon#419]
There are levels 1-3  in PII data. Level 1 is publicly known information such as the person's name or social media handles.

Level 2 examples (semi-private data)
- Address
- Age

Level 3 examples (fully private data)
- Social Security Number
- Medical History

Initially, we want to detect if an object contains PII data levels 2-3. 

For example, this should be detected (contains email, phone, SSN, and age):
```
user_data = {
    "name": "John Doe",
    "twitter_handle": "@john_doe",
    "email": "john.doe@example.com",
    "phone": "123-456-7890",
    "SSN": "123-45-6789"
    "Age": 29
}
```

However, this shouldn't be detected:
```
user_data = {
    "name": "John Doe",
    "twitter_handle": "@john_doe"
}
```

**Comment by javidal10** [comment]
# PII Data Detection Implementation

## Regex Patterns for Key Names

To effectively filter PII and PIII level data based on key names, I established regex patterns that match common key naming conventions.

### PII Level 2 Keys (Semi-Private Data)

```javascript
const PII_LEVEL_2_KEYS = [
    /^(address|street|location|city|state|zipcode|postalCode)$/i, // Address-related keys
    /^(age|dateOfBirth)$/i // Age-related keys
];
```

### PII Level 3 Keys (Fully Private Data)

```javascript
const PII_LEVEL_3_KEYS = [
    /^(ssn|socialSecurityNumber)$/i, // Social Security Number
    /^(medicalHistory|medicalRecords|healthHistory)$/i // Medical history-related keys
];
```

## Regex Key Filter Function

```javascript
function filterPIIData(userData) {
    const piiData = {};

    for (const key in userData) {
        if (userData.hasOwnProperty(key)) {
            const lowerCaseKey = key.toLowerCase();

            if (PII_LEVEL_2_KEYS.some(regex => regex.test(lowerCaseKey)) || 
                PII_LEVEL_3_KEYS.some(regex => regex.test(lowerCaseKey))) {
                piiData[key] = userData[key];
            }
        }
    }

    return piiData;
}
```

### Considerations
- Regex Patterns Adaptation: The provided regex patterns are designed to cover common key naming conventions.

- Case Sensitivity: The regex patterns use the 'i' flag to ensure case-insensitive matching, accommodating keys in various case formats.

**Comment by baristaGeek** [comment]
**Notes from feedback of a user:**

- Proposed regexes are only considering camel case. We should consider other notations such as `postal_code`, `postal-code`, `PostalCode`, etc. 
- PHI (Protected Health Information) keywords should be included. Also for other domains (maybe something to think about in a separate task)
- Keywords itself might not even be enough. Other patterns that detect disease names, addresses, etc.

**Comment by baristaGeek** [comment]
Deployed a version of this!
